language: node_js
node_js: ["6"]

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test:build
  - DEBUG=true yarn test:coverage

deploy:
  provider: script
  script: scripts/travisDeploy.bash
  on:
    tags: true
