language: node_js
node_js: ["6"]

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test:build
  - DEBUG=true yarn test:coverage

deploy:
  - provider: script
    script: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    on: { tags: true }
  - provider: script
    script: npm run release
    on: { tags: true }
